# Funding options for Neo Design System
# These are supported funding model platforms

github: [fabiobrunning]
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie:
# lfx_crowdfunding:
custom: ['https://neoloop.com.br/sponsor']
