export { createIcon } from "./create-icon";
export type { IconProps } from "./create-icon";

export {
  HomeIcon,
  MenuIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  XIcon,
  SearchIcon,
  PlusIcon,
  MinusIcon,
  EditIcon,
  TrashIcon,
  CopyIcon,
  DownloadIcon,
  UploadIcon,
  CheckIcon,
  AlertCircleIcon,
  InfoIcon,
  XCircleIcon,
  SettingsIcon,
  UserIcon,
  EyeIcon,
  EyeOffIcon,
  SunIcon,
  MoonIcon,
  LoaderIcon,
} from "./icons";

import {
  HomeIcon,
  MenuIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  XIcon,
  SearchIcon,
  PlusIcon,
  MinusIcon,
  EditIcon,
  TrashIcon,
  CopyIcon,
  DownloadIcon,
  UploadIcon,
  CheckIcon,
  AlertCircleIcon,
  InfoIcon,
  XCircleIcon,
  SettingsIcon,
  UserIcon,
  EyeIcon,
  EyeOffIcon,
  SunIcon,
  MoonIcon,
  LoaderIcon,
} from "./icons";

export const iconRegistry = {
  home: HomeIcon,
  menu: MenuIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-up": ChevronUpIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  x: XIcon,
  search: SearchIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  edit: EditIcon,
  trash: TrashIcon,
  copy: CopyIcon,
  download: DownloadIcon,
  upload: UploadIcon,
  check: CheckIcon,
  "alert-circle": AlertCircleIcon,
  info: InfoIcon,
  "x-circle": XCircleIcon,
  settings: SettingsIcon,
  user: UserIcon,
  eye: EyeIcon,
  "eye-off": EyeOffIcon,
  sun: SunIcon,
  moon: MoonIcon,
  loader: LoaderIcon,
} as const;

export type IconName = keyof typeof iconRegistry;
